### ISSUE TITLE
Default roundedCornerWidth doesn't match progressWidth = 4

### ISSUE THREAD

**Issue by blixt** [kirualex/KAProgressLabel#15]
This configuration worked in v2.1.

![screen shot 2015-03-19 at 4 50 46 pm](https://cloud.githubusercontent.com/assets/158591/6741171/c877deee-ce5b-11e4-888e-aa7c4d16e1b3.png)

Here's how I set it up:

```obj-c
KAProgressLabel *uploadProgress = [[KAProgressLabel alloc] initWithFrame:CGRectMake(0, 0, 26, 26)];
uploadProgress.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleBottomMargin;
uploadProgress.center = CGPointMake(self.contentView.bounds.size.width - 36, self.contentView.center.y);
uploadProgress.hidden = YES;
uploadProgress.progressWidth = 4;
uploadProgress.trackColor = [UIColor colorForRogerProgressBackground];
uploadProgress.trackWidth = 6;
[self.contentView addSubview:uploadProgress];
self.uploadProgress = uploadProgress;
```

**Comment by blixt** [comment]
Trying to use `uploadProgress.roundedCornersWidth = 3;` doesn't change the appearance at all, while using `uploadProgress.roundedCornersWidth = 2;` results in the rounded corners disappearing altogether:

![screen shot 2015-03-19 at 5 22 36 pm](https://cloud.githubusercontent.com/assets/158591/6741296/bfb98874-ce5c-11e4-9dbc-38e220eb51a7.png)

**Comment by kirualex** [comment]
This is odd. Did you try explicitly setting `uploadProgress..roundedCorners = YES;`?

**Comment by blixt** [comment]
@kirualex Specifying `roundedCorners = YES` doesn't change anything (which I guess is because it's the default?) and setting them to `NO` gives the expected appearance (like the second screenshot above).

**Comment by kirualex** [comment]
hmmm, could you try with the dev branch? I think there may be a bug on the 3.0 here... I'll try to patch this up tomorrow.

**Comment by kirualex** [comment]
I pushed a rather big refactoring :  `pod 'KAProgressLabel'  => '3.1'`
- No more `KAProgressTypeRect`, this library now focuses on circular progress. This also reduce code overhead.
- No more `clockWise` property, the effect is achievable via `startDegree` and `endDegree` anyway
- No more `roundedCorners` boolean property, `roundedCornersWidth` now need an explicit value (default to 0)

Let me know if you have issues with it, the adaptations should be straightforward. I may not be finished with refactoring, but this is a good start.

**Comment by blixt** [comment]
I tried out v3.1 and now the progress bars don't have rounded ends by default (like you said). If I set the `roundedCornersWidth` property to `4`, I get this:
![screen shot 2015-03-20 at 2 50 39 pm](https://cloud.githubusercontent.com/assets/158591/6758751/ec7bf70c-cf10-11e4-94e4-581def95b220.png)

Here's the setup code:
```obj-c
KAProgressLabel *uploadProgress = [[KAProgressLabel alloc] initWithFrame:CGRectMake(0, 0, 26, 26)];
uploadProgress.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleTopMargin | UIViewAutoresizingFlexibleBottomMargin;
uploadProgress.center = CGPointMake(self.contentView.bounds.size.width - 36, self.contentView.center.y);
uploadProgress.hidden = YES;
uploadProgress.progressWidth = 4;
uploadProgress.roundedCornersWidth = 4;
uploadProgress.trackColor = [UIColor colorForRogerProgressBackground];
uploadProgress.trackWidth = 6;
[self.contentView addSubview:uploadProgress];
self.uploadProgress = uploadProgress;
```

**Comment by kosyak** [comment]
Shouldn't `-(void)drawRect:(CGRect)rect` in `KAProgressLabel.m` rely on `self.bounds` instead of `rect` if it's not planned to redraw only the part of the `KAProgressLabel `'s frame? I've had the same issue and replacing `rect` with `self.bounds` there worked for me. Unfortunately, couldn't pull together a demo to show this kind of behaviour.

**Comment by kirualex** [comment]
@kosyak I don't really understand where the problem is with relying on the `rect` parameter. Could you provide some more details on this in a dedicated issue? (I'm closing this one)

**Comment by blixt** [comment]
@kirualex Why close this one? The bug still persists. Is there another issue tracking this bug?

**Comment by kirualex** [comment]
My bad I thought it was, reopening

**Comment by kirualex** [comment]
After some fiddling I'm scratching my head on this one, I'll have a look next week.

**Comment by hobbesthetige** [comment]
I am also having this problem.

progressView.trackWidth = 6.0
progressView.progressWidth = 6.0
progressView.roundedCornersWidth = 5.0

![screenshot 2015-08-18 10 55 27](https://cloud.githubusercontent.com/assets/4026614/9333396/aaf8bd6c-4597-11e5-8a00-6ce05ae5684f.png)

**Comment by tikhop** [comment]
@kirualex, @hobbesthetige I've come across the same issue and the easiest way to resolve the problem is just subclass UIView instead of UILabel.

**Comment by kosyak** [comment]
Way too late to report, but in my case, https://github.com/kirualex/KAProgressLabel/commit/2cb335ccd57d44ee825902c496e6029874f771f4 resolved this issue 👍
